"""empty message

Revision ID: 351fc6e2518f
Revises: 
Create Date: 2021-11-27 13:50:38.246638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '351fc6e2518f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('loc', sa.String(length=255), nullable=True),
    sa.Column('inc_7d', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entry')
    # ### end Alembic commands ###
